Has problem with revert

diff --git a/install/control b/install/control
--- a/install/control
+++ b/install/control
@@ -10,94 +10,96 @@ function saveSnapshot(){
 			break
 		fi
 	done
-	virsh snapshot-create-as --domain $1 $randString --diskspec vda,file=$SNAPSHOTDIR/$randString"disk",snapshot=external --memspec file=$SNAPSHOTDIR/$randString"mem",snapshot=external --atomic
-#####should add if return is not 
+	if ! virsh -q snapshot-create-as --domain $1 $randString --diskspec vda,file=$SNAPSHOTDIR/$randString"disk",snapshot=external --memspec file=$SNAPSHOTDIR/$randString"mem",snapshot=external --atomic ; then
+		#live?
+		echo "Error in save snapshot" >&2
+	fi
 	local prevSave=$(sqlite3 -batch vminfo.db "SELECT PATH FROM FS WHERE NAME = '$1';")
 	sqlite3 -batch vminfo.db "UPDATE FS SET PATH = '$randString' WHERE NAME ='$1';"
-	if [ $prevSave != "INIT" ]; then
-		rm $SNAPSHOTDIR/$prevSave"mem"
-		rm $SNAPSHOTDIR/$prevSave"disk"
-	fi
+	#if [ $prevSave != "INIT" ]; then
+	#	rm $SNAPSHOTDIR/$prevSave"mem"
+	#	rm $SNAPSHOTDIR/$prevSave"disk"
+	#fi
 	return 0
 }
 
 function loadSnapshot(){
 	local snapshotName=$(sqlite3 -batch vminfo.db "SELECT PATH FROM FS WHERE NAME = '$1';")
-	virsh snapshot-restore $1 $snapshotName
+	virsh snapshot-revert $1 $snapshotName
 	return 0
 }
 
 function initOnDemand(){
-	if [ sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';"|wc -l ]; then
+	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';") ]; then
 		sqlite3 -batch vminfo.db "DELETE FROM FS WHERE NAME='$1';"
 	fi
-	if [ sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';"|wc -l ]; then
+	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';") ]; then
 		sqlite3 -batch vminfo.db "DELETE FROM VM WHERE NAME='$1';"
 	fi
 
-	if [ sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_ONDEMAND',NULL,$(date +%s3N),NULL,0);" ];then
-		echo "Error in saving DB." &>2
+	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_ONDEMAND',NULL,$(date +%s%3N),NULL,0);" ; then
+		echo "Error in saving DB." >&2
 		return 1
 	fi
-	if [ sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ];then
-		echo "Error in saving DB." &>2
+	if ! sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ;then
+		echo "Error in saving DB." >&2
 		return 1
 	fi
 	changeStatus $1 "RUN_ONDEMAND" && saveSnapshot $1
-	return $_
+	return $?
 }
 
 function initSpot(){
-	if [ sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';"|wc -l ]; then
+	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';") ] ; then
 		sqlite3 -batch vminfo.db "DELETE FROM FS WHERE NAME='$1';"
 	fi
-	if [ sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';"|wc -l ]; then
+	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';") ] ; then
 		sqlite3 -batch vminfo.db "DELETE FROM VM WHERE NAME='$1';"
 	fi
 
-	if [ sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_SPOT',$DEFAULT_SAVE_INTERVAL,$(date +%s3N),$2,0);" ];then
-		echo "Error in saving DB." $&>2
+	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_SPOT',$DEFAULT_SAVE_INTERVAL,$(date +%s3N),$2,0);" ;then
+		echo "Error in saving DB." >&2
 		return 1
 	fi
-	if [ sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ];then
-		echo "Error in saving DB." $&>2
+	if ! sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ;then
+		echo "Error in saving DB." >&2
 		return 1
 	fi
 	changeStatus $1 "RUN_SPOT" && saveSnapshot $1
-	return $_
+	return $?
 }
 
 function changeStatus(){
-	local prevStatus = $(sqlite3 -batch vminfo.db "SELECT STATUS WHERE NAME = $1 ;")
-	local curTime = $(data +%s3N)
+	local prevStatus=$(sqlite3 -batch vminfo.db "SELECT STATUS FROM VM WHERE NAME = '$1' ;")
+	local curTime=$(date +%s%3N)
 	case $prevStatus in
 		"RUN_SPOT_NO_SAVE")
-			local prevTime = $(sqlite3 -batch vminfo.db "SELECT TURN_ON_TIME WHERE NAME = $1 ;")
+			local prevTime = $(sqlite3 -batch vminfo.db "SELECT TURN_ON_TIME WHERE NAME = '$1' ;")
 			local price = $(sqlite3 -batch vminfo.db "SELECT PRICE WHERE MODE = 'SPOT';")
-			if [ sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME =$1 ;" ]; then
-				echo "Error in saving DB." &>2
+			if ! sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME = '$1' ;" ; then
+				echo "Error in saving DB." >&2
 				return 1
 			fi
 			;;
 		"RUN_SPOT")
 			local prevTime = $(sqlite3 -batch vminfo.db "SELECT TURN_ON_TIME WHERE NAME = $1 ;")
 			local price = $(sqlite3 -batch vminfo.db "SELECT PRICE WHERE MODE = 'SPOT';")
-			if [ sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME =$1 ;" ]; then
-				echo "Error in saving DB." &>2
+			if ! sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME = '$1' ;" ; then
+				echo "Error in saving DB." >&2
 				return 1
 			fi
 			;;
 		"RUN_ONDEMAND")
 			local prevTime = $(sqlite3 -batch vminfo.db "SELECT TURN_ON_TIME WHERE NAME = $1 ;")
 			local price = $(sqlite3 -batch vminfo.db "SELECT PRICE WHERE MODE = 'ONDEMAND';")
-			if [ sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME =$1 ;" ]; then
-				echo "Error in saving DB." &>2
+			if ! sqlite3 -batch vminfo.db "UPDATE VM SET BILL = BILL + $(echo "($curTime-$prevTime)*price"|bc -l) WHERE NAME = '$1' ;" ; then
+				echo "Error in saving DB." >&2
 				return 1
 			fi
 			;;
 	esac
-	if [ sqlite3 -batch vminfo.db "UPDATE VM SET STATUS = $2 , TURN_ON_TIME = $curTime WHERE NAME = $1 ;" ]; then
-		echo "Error in saving DB." &>2
+	if ! sqlite3 -batch vminfo.db "UPDATE VM SET STATUS = '$2' , TURN_ON_TIME = $curTime WHERE NAME = '$1' ;" ; then
+		echo "Error in saving DB." >&2
 		return 1
 	fi
 	return 0
@@ -105,12 +107,12 @@ function changeStatus(){
 
 function changePrice(){
 	if [[ ! $2 =~ ^[+-]?[0-9]+\.?[0-9]*$ ]];then
-		echo "Please check the parameters. The price is not float value." &>2
+		echo "Please check the parameters. The price is not float value." >&2
 		return 1
 	fi
 
 	if [ sqlite3 -batch vminfo.db "UPDATE VM SET SPOT_PRICE = $2 WHERE NAME = $1;" ]; then
-		echo "Error in saving DB." &>2
+		echo "Error in saving DB." >&2
 		return 1
 	fi
 	return 0
@@ -118,7 +120,7 @@ function changePrice(){
 
 function getCurrentPrice(){
 	if [[ ! $1 =~ ^(SPOT|ONDEMAND)$ ]]; then
-		echo "Please check the parameters. There is no $1 mode." &>2
+		echo "Please check the parameters. There is no $1 mode." >&2
 		return 1
 	fi
 	echo $(sqlite3 -batch vminfo.db "SELECT PRICE WHERE MODE = $1 ;")
@@ -127,15 +129,15 @@ function getCurrentPrice(){
 
 function changeCurrentPrice(){
 	if [[ ! $2 =~ ^[+-]?[0-9]+\.?[0-9]*$ ]];then
-		echo "Please check the parameters. The price is not float value." &>2
+		echo "Please check the parameters. The price is not float value." >&2
 		return 1
 	fi
 	if [[ ! $1 =~ ^(SPOT|ONDEMAND)$ ]]; then
-		echo "Please check the parameters. There is no $1 mode." &>2
+		echo "Please check the parameters. There is no $1 mode." >&2
 		return 1
 	fi
 	if [ sqlite3 -batch vminfo.db "UPDATE GB SET PRICE = $2 WHERE MODE = $1 ;" ]; then
-		echo "Error in saving DB." &>2
+		echo "Error in saving DB." >&2
 		return 1
 	fi
 	return 0
@@ -145,62 +147,66 @@ function changeCurrentPrice(){
 ACSDIR=/etc/acs/
 
 if [ "$(id -u)" -ne 0 ]; then
-	echo 'Please run as root or using sudo.'&>2
+	echo 'Please run as root or using sudo.' >&2
 	exit 1
 fi
 
-if [ -d $ACSDIR ]; then
-	echo "ACS is not installed. Please execute install.sh first"&>2
+if [ ! -d $ACSDIR ]; then
+	echo "ACS is not installed. Please execute install.sh first" >&2
 	exit 1
 fi
 
-if [ ! 	virsh list --all|sed 1,2d |grep -w -q $2 ]; then
-	echo "There is no such name." &>2
+#if [ "$#" -lt 2 ]; then
+#	echo "Please check the number of parameters" >&2
+#	exit 1
+#fi
+
+if [ -z $(virsh list --all | awk '{print $2}'|sed 1,2d | grep -w $1) ]; then
+	echo "There is no such name." >&2
 	exit 1
 fi
 
 cd $ACSDIR
-
-case $1 in
+case $2 in
 	"INIT_ONDEMAND")
-		if [ "$#" -ne 3 ]; then
-			echo 'Please check the number of parameters.' &>2
+		if [ "$#" -ne 2 ]; then
+			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		initOnDemand $2 $3
-		exit $_
+		initOnDemand $1
+		exit $?
 		;;
 	"INIT")
 		if [ "$#" -ne 3 ]; then
-			echo 'Please check the number of parameters.' &>2
+			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		initSpot $2 $3
-		exit $_
+		initSpot $1 $3
+		exit $?
 		;;
 	"CHANGE_STATUS")
 		if [ "$#" -ne 3 ]; then
-			echo 'Please check the number of parameters.' &>2
+			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changeStatus $2 $3
-		exit $_
+		changeStatus $1 $3
+		exit $?
 		;;
 	"CHAGE_PRICE")
 		if [ "$#" -ne 3 ]; then
-			echo 'Please check the number of parameters.' &>2
+			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changePrice $2 $3
-		exit $_
+		changePrice $1 $3
+		exit $?
 		;;
 	"CHANGE_GLOBAL_PRICE")
 		if [ "$#" -ne 3 ]; then
-			echo 'Please check the number of parameters.' &>2
+			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changeCurrentPrice $2 $3
-		exit $_
+		changeCurrentPrice $1 $3
+		exit $?
 		;;
 esac
 
