Almost done

diff --git a/virtualBox/control b/virtualBox/control
--- a/virtualBox/control
+++ b/virtualBox/control
@@ -2,73 +2,97 @@
 
 DEFAULT_SAVE_INTERVAL=20
 
-function saveSnapshot(){
+#complite
+function getNameFromIP(){
+	VBoxManage list runningvms | cut -d "{" -f1 | sed "s/\"//g" | while read VBOXNAME; do
+    	IP=$(VBoxManage guestproperty get "$VBOXNAME" /VirtualBox/GuestInfo/Net/1/V4/IP | cut -d":" -f2)
+	if [ $IP = $1 ]; then
+		echo "$VBOXNAME"
+		return 0
+	fi
+	done
+	return 0
+}
+
+#complite
+function getUnusedName(){
+#length should be modified
 	local randString=''
 	while : ; do
-		randString=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 30)
-		if [ ! -f $randString"mem" ] ; then
+		randString=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)
+		if  ! VBoxManage list vms | awk '{print $1}'| grep -q "$randString" ; then
 			break
 		fi
 	done
-	if ! virsh -q snapshot-create-as --domain $1 $randString --diskspec vda,file=$SNAPSHOTDIR/$randString"disk",snapshot=external --memspec file=$SNAPSHOTDIR/$randString"mem",snapshot=external --atomic ; then
-		#live?
+	echo $randString
+	return 0
+}
+
+#complite
+function saveSnapshot(){
+	local randString=$(getUnusedName)
+	if ! VBoxManage controlvm $1 savestate ; then
 		echo "Error in save snapshot" >&2
 	fi
-	local prevSave=$(sqlite3 -batch vminfo.db "SELECT PATH FROM FS WHERE NAME = '$1';")
-	sqlite3 -batch vminfo.db "UPDATE FS SET PATH = '$randString' WHERE NAME ='$1';"
-	#if [ $prevSave != "INIT" ]; then
-	#	rm $SNAPSHOTDIR/$prevSave"mem"
-	#	rm $SNAPSHOTDIR/$prevSave"disk"
-	#fi
-	return 0
-}
-
-function loadSnapshot(){
-	local snapshotName=$(sqlite3 -batch vminfo.db "SELECT PATH FROM FS WHERE NAME = '$1';")
-	virsh snapshot-revert $1 $snapshotName
-	return 0
-}
-
-function initOnDemand(){
-	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';") ]; then
-		sqlite3 -batch vminfo.db "DELETE FROM FS WHERE NAME='$1';"
+	local prevStatus=$(sqlite3 -batch vminfo.db "SELECT PREV_STATE FROM VM WHERE NAME = '$1' ;")
+	if ! VBoxManage clonevm $1 --name $randString && VBoxManage unregistervm --delete $prevStatus; then
+		echo "Error in save snapshot" >&2
 	fi
+	if ! sqlite3 -batch vminfo.db "INSERT INTO VM ('$randString',STATUS,SAVE_INTERVAL,TURN_ON_TIME,SPOT_PRICE,BILL,START_NAME,'$1') SELECT * FROM VM WHERE NAME = '$1';" && sqlite3 -batch vminfo.db "DELETE FROM VM WHERE NAME='$1'"; then
+		echo "Error in saving DB." >&2
+		return 1
+	fi
+	VBoxManage startvm $randString --type headless&
+	return 0
+}
+
+#complite
+function loadSnapshot(){
+	local prevStatus=$(sqlite3 -batch vminfo.db "SELECT PREV_STATE FROM VM WHERE NAME = '$1' ;")
+	VBoxManage clonevm $prevStatus --name $1 && VBoxManage startvm $1 --type headless
+	return 0
+}
+
+#complite
+function initOnDemand(){
 	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';") ]; then
 		sqlite3 -batch vminfo.db "DELETE FROM VM WHERE NAME='$1';"
 	fi
 
-	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_ONDEMAND',NULL,$(date +%s%3N),NULL,0);" ; then
+	if ! VBoxManage controlvm $1 savestate ; then
+		echo "Error in save snapshot" >&2
+	fi
+	
+	snapshotName=$(getUnusedName)
+	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$snapshotName','READY_ONDEMAND',NULL,$(date +%s%3N),NULL,0,'$1','$1');" ;then
 		echo "Error in saving DB." >&2
 		return 1
 	fi
-	if ! sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ;then
-		echo "Error in saving DB." >&2
-		return 1
-	fi
-	changeStatus $1 "RUN_ONDEMAND" && saveSnapshot $1
+	changeStatus $1 "RUN_ONDEMAND"
+	loadSnapshot $1 $snapshotName
 	return $?
 }
 
+#complite
 function initSpot(){
-	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM FS WHERE NAME='$1';") ] ; then
-		sqlite3 -batch vminfo.db "DELETE FROM FS WHERE NAME='$1';"
-	fi
+	echo "in initspot $1 $2"
 	if [ ! -z $(sqlite3 -batch vminfo.db "SELECT * FROM VM WHERE NAME='$1';") ] ; then
 		sqlite3 -batch vminfo.db "DELETE FROM VM WHERE NAME='$1';"
 	fi
-
-	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$1','READY_SPOT',$DEFAULT_SAVE_INTERVAL,$(date +%s3N),$2,0);" ;then
+	if ! VBoxManage controlvm $1 savestate ; then
+		echo "Error in save snapshot" >&2
+	fi
+	snapshotName=$(getUnusedName)
+	if ! sqlite3 -batch vminfo.db "INSERT INTO VM VALUES ('$snapshotName','READY_SPOT',$DEFAULT_SAVE_INTERVAL,$(date +%s%3N),$2,0,'$1','$1');" ;then
 		echo "Error in saving DB." >&2
 		return 1
 	fi
-	if ! sqlite3 -batch vminfo.db "INSERT INTO FS VALUES ('$1','INIT');" ;then
-		echo "Error in saving DB." >&2
-		return 1
-	fi
-	changeStatus $1 "RUN_SPOT" && saveSnapshot $1
+	changeStatus $snapshotName "RUN_SPOT"
+	loadSnapshot $snapshotName
 	return $?
 }
 
+#complite
 function changeStatus(){
 	local prevStatus=$(sqlite3 -batch vminfo.db "SELECT STATUS FROM VM WHERE NAME = '$1' ;")
 	local curTime=$(date +%s%3N)
@@ -105,6 +129,7 @@ function changeStatus(){
 	return 0
 }
 
+#complite
 function changePrice(){
 	if [[ ! $2 =~ ^[+-]?[0-9]+\.?[0-9]*$ ]];then
 		echo "Please check the parameters. The price is not float value." >&2
@@ -118,16 +143,20 @@ function changePrice(){
 	return 0
 }
 
+#complite
 function getCurrentPrice(){
+#getCurrentPrice {SPOT,ONDEMAND}
 	if [[ ! $1 =~ ^(SPOT|ONDEMAND)$ ]]; then
 		echo "Please check the parameters. There is no $1 mode." >&2
 		return 1
 	fi
-	echo $(sqlite3 -batch vminfo.db "SELECT PRICE WHERE MODE = $1 ;")
+	echo $(sqlite3 -batch vminfo.db "SELECT PRICE FROM GB WHERE MODE = $1 ;")
 	return 0
 }
 
+#complite
 function changeCurrentPrice(){
+#changeCurrentPrice {SPOT,ONDEMAND} price
 	if [[ ! $2 =~ ^[+-]?[0-9]+\.?[0-9]*$ ]];then
 		echo "Please check the parameters. The price is not float value." >&2
 		return 1
@@ -143,37 +172,58 @@ function changeCurrentPrice(){
 	return 0
 }
 
+#complite
+function changeSaveInterval(){
+#changeSaveInterval vmName interval
+	if [[ ! $2 =~ ^[+-]?[0-9]+$ ]];then
+		echo "Please check the parameters. The price is not integer value." >&2
+		return 1
+	fi
+	if [ sqlite3 -batch vminfo.db "UPDATE VM SET SAVE_INTERVAL = $2 WHERE NAME = $1 ;" ]; then
+		echo "Error in saving DB." >&2
+		return 1
+	fi
+	return 0
+}
 
-ACSDIR=/etc/acs/
+ACSDIR=~/acs/
 
-if [ "$(id -u)" -ne 0 ]; then
-	echo 'Please run as root or using sudo.' >&2
-	exit 1
-fi
+#if [ "$(id -u)" -ne 0 ]; then
+#	echo 'Please run as root or using sudo.' >&2
+#	exit 1
+#fi
 
 if [ ! -d $ACSDIR ]; then
 	echo "ACS is not installed. Please execute install.sh first" >&2
 	exit 1
 fi
 
-#if [ "$#" -lt 2 ]; then
-#	echo "Please check the number of parameters" >&2
-#	exit 1
-#fi
+cd $ACSDIR
 
-if [ -z $(virsh list --all | awk '{print $2}'|sed 1,2d | grep -w $1) ]; then
-	echo "There is no such name." >&2
-	exit 1
+case $1 in
+	"CHANGE_GLOBAL_PRICE")
+		if [ "$#" -ne 3 ]; then
+			echo 'Please check the number of parameters.' >&2
+			exit 1
+		fi
+		changeCurrentPrice $1 $3
+		exit $?
+		;;
+esac
+
+vmName=$(getNameFromIP $1)
+if [ -z "$vmName" ]; then
+	echo 'There is no such IP.' >&2
+	exit 0
 fi
 
-cd $ACSDIR
 case $2 in
 	"INIT_ONDEMAND")
 		if [ "$#" -ne 2 ]; then
 			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		initOnDemand $1
+		initOnDemand $vmName
 		exit $?
 		;;
 	"INIT")
@@ -181,7 +231,7 @@ case $2 in
 			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		initSpot $1 $3
+		initSpot $vmName $3
 		exit $?
 		;;
 	"CHANGE_STATUS")
@@ -189,7 +239,7 @@ case $2 in
 			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changeStatus $1 $3
+		changeStatus $vmName $3
 		exit $?
 		;;
 	"CHAGE_PRICE")
@@ -197,15 +247,15 @@ case $2 in
 			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changePrice $1 $3
+		changePrice $vmName $3
 		exit $?
 		;;
-	"CHANGE_GLOBAL_PRICE")
+	"CHANGE_SAVE_INTERVAL")
 		if [ "$#" -ne 3 ]; then
 			echo 'Please check the number of parameters.' >&2
 			exit 1
 		fi
-		changeCurrentPrice $1 $3
+		changeSaveInterval $vmName $3
 		exit $?
 		;;
 esac
